{{ if .Values.policies.imagesNeedsToBeSigned }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ .Values.policies.imagesNeedsToBeSigned.name }}
spec:
  validationFailureAction: {{ .Values.policies.imagesNeedsToBeSigned.validationAction }}
  rules:
    - name: "{{ .Values.policies.imagesNeedsToBeSigned.name }}-rule"
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
      {{ range .Values.policies.imagesNeedsToBeSigned.imagesAndPublicKeyPairs }}
        - imageReferences:
            - {{ .image }}
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
{{ .key | indent 22 }}

      {{ end }}
{{ end }}