{{ if .Values.policies.imagesNeedsToBeSigned.enabled }}
{{ with .Values.policies.imagesNeedsToBeSigned }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ .name }}
spec:
  validationFailureAction: {{ .validationAction }}
  rules:
    - name: "{{ .name }}-rule"
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
      {{ range .imagesAndPublicKeyPairs }}
        - imageReferences:
            - {{ .image }}
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
{{ .key | indent 22 }}

      {{ end }}

{{ end }}
{{ end }}