{{ with .Values.customPolicies.disallowUnspecifiedDockerRegistries }}
{{ if .enabled }}

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ .name }}
spec:
  validationFailureAction: {{ .validationAction }}
  background: {{.background}}
  rules:
    - name: "{{ .name }}-rule"
      match:
        any:
          - resources:
              kinds:
                - Pod

      validate:
        message: "Unknown image registry."
        pattern:
          spec:
            containers:
              - image: {{ join " | " .registryUrls | quote}}

      exclude:
        any:
          - resources:
              namespaces:
              {{- range .excludeNamespaces }}
                - {{ . }}
              {{- end }}
{{ end }}
{{ end }}