kyverno:
  # This parameter controls if kyverno (dependency) should be installed or not.
  # This option is by default on false but can be set to true.
  # This makes it easier to use the chart in an umbrella chart.
  install: false


policies:

  # settings for the policy which verifies if images from specific sources are signed.
  imagesNeedsToBeSigned:

    # Enables or disables this policy
    # Only accepts true or false as values
    enabled: false

    # The name of the policy
    name: image-needs-to-be-signed-policy

    # This parameter handles how a policy violation is handled.
    #
    # Allowed values are:
    # - enforce
    # - audit
    #
    # If a policy is violated and the action is "enforce", then the ressource will not be allowed
    # to be created. On the other  the "audit" action allows the ressource but reports this incident.
    #
    # For more information check out the documentation of Kyverno:
    # https://kyverno.io/docs/writing-policies/validate/
    validationAction: "enforce"

    # A list of images and public key pairs.
    #
    # The image has to be a fully qualified path to the image(s).
    # You need to prepend always the registry.
    # The image(s) will be verified with the given public key.
    #
    # Wildcards are supported.
    # For more information check out: https://kyverno.io/docs/writing-policies/validate/#wildcards
    imagesAndPublicKeyPairs:
      - image: "docker.io/iits/*"
        key: |-
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXzV8f2YUEmXF176k//uSmgEEZoKb
          g2b7+PuoKjfaYVw3HTAE2Z4ak5ZNNq5HF8G1cRt3P713MyuIXiNKP6v2Nw==
          -----END PUBLIC KEY-----

    # A list of namespaces which are going to be excluded
    #
    # Wildcards are supported.
    # For more information check out: https://kyverno.io/docs/writing-policies/validate/#wildcards
    excludeNamespaces:
      - "kube-*"
      - "tests"

    # These values control the tests.
    # The tests for this policy will only be run if the relevant values are set.
    test:

      # A signed image to test if a signed image can be deployed to the cluster
      signedImage: "iits/git-jq:1.2.0"

      # An unsigned image with an excluded namespace to test if an unsigned image can be deployed to an excluded
      # namespace in the cluster.
      unsignedImage: "iits/git-jq:1.0.0"
      excludeNamespace: "tests"

  onlyFormSpecificDockerRegistry:

    # Enables or disables this policy
    # Only accepts true or false as values
    enabled: true

    # The name of the policy
    name: only-from-specific-docker-registry

    # List of allowed registries
    #
    # Wildcards are supported.
    # For more information check out: https://kyverno.io/docs/writing-policies/validate/#wildcards
    registryUrls:
      - "harbor.docker.svc.cluster.local:9000/*"
      - "registry.gitlab.com/impresssol/*"
      - "iits/*"

    # This parameter handles how a policy violation is handled.
    #
    # Allowed values are:
    # - enforce
    # - audit
    #
    # If a policy is violated and the action is "enforce", then the ressource will not be allowed
    # to be created. On the other  the "audit" action allows the ressource but reports this incident.
    #
    # For more information check out the documentation of Kyverno:
    # https://kyverno.io/docs/writing-policies/validate/
    validationAction: "enforce"

    # A list of namespaces which are going to be excluded
    #
    # Wildcards are supported.
    # For more information check out: https://kyverno.io/docs/writing-policies/validate/#wildcards
    excludeNamespaces:
      - "kube-*"
      - "tests"

    # These values control the tests.
    # The tests for this policy will only be run if the relevant values are set.
    test:

      # A signed image to test if a signed image can be deployed to the cluster
      imageAllowedRegistry: "iits/git-jq:1.2.0"

      # An unsigned image with an excluded namespace to test if an unsigned image can be deployed to an excluded
      # namespace in the cluster.
      imageForbiddenRegistry: "busybox:latest"
      excludeNamespace: "tests"